# Enables Travis to use their new container-based infrastructure
sudo: false

# Build for Ruby
language: ruby

# Enables caching for bundler
cache: bundler

# Specify which ruby versions you wish to run your tests on, each version will be used
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  # - ruby-head
  # - jruby

# Define how to run your tests (defaults to `bundle exec rake` or `rake` depending on whether you have a `Gemfile`)
script: "bundle exec rake"

# Define tasks to be completed before and after tests run . Will allow folding of content on frontend
#before_script:
#  - command_1
#  - command_2
#
#after_script:
#  - command_1
#  - command_2

# Specify an ENV variable to run before: 'bundle install' and 'rake' (or your defined 'script')
env:
  - CI=1

# Specify the recipients for email notification
#notifications:
#  recipients:
#    - email-address-1
#    - email-address-2

# Disable email notifications
#notifications:
#  disabled: true

# notifications:
#   webhooks:
#     urls:
#       - https://webhooks.gitter.im/e/c6dbb9323007dfcf81df
