# Passes arguments to bundle install (http://gembundler.com/man/bundle-install.1.html)
# bundler_args:

# Specify which ruby versions you wish to run your tests on, each version will be used
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
#  - jruby      # see http://jira.codehaus.org/browse/JRUBY-7007
#  - ruby-head  # RedCloth does not compile on head
#  - 1.8.6      # Does not work on travis-ci
#  - 1.9.1      # Does not work on travis-ci
#  - 1.9.2      # Does not work on travis-ci ..really?
#  - ree        # Does not work on travis-ci ..really?

# Define how to run your tests (defaults to `bundle exec rake` or `rake` depending on whether you have a `Gemfile`)
script: "bundle exec rake travis_ci"

# Define tasks to be completed before and after tests run . Will allow folding of content on frontend
#before_script:
#  - command_1
#  - command_2
#
#after_script:
#  - command_1
#  - command_2

# Specify an ENV variable to run before: 'bundle install' and 'rake' (or your defined 'script')
env: "CI=1 SUITE=1 "

# Specify the recipients for email notification
#notifications:
#  recipients:
#    - email-address-1
#    - email-address-2

# Disable email notifications
#notifications:
#  disabled: true
