# Passes arguments to bundle install (http://gembundler.com/man/bundle-install.1.html)
#bundler_args: --binstubs

# Specify which ruby versions you wish to run your tests on, each version will be used
rvm:
  - 1.9.2
  - 1.9.1
  - 1.8.7
  - 1.8.6
  - ree
  - jruby
  - ruby-head

# Define how to run your tests (defaults to `bundle exec rake` or `rake` depending on whether you have a `Gemfile`)
script: "rake travis_ci"

# Define tasks to be completed before and after tests run . Will allow folding of content on frontend
#before_script:
#  - command_1
#  - command_2
#
#after_script:
#  - command_1
#  - command_2

# Specify an ENV variable to run before: 'bundle install' and 'rake' (or your defined 'script')
env: "CI=1 SUITE=1 "

# Specify the recipients for email notification
#notifications:
#  recipients:
#    - email-address-1
#    - email-address-2

# Disable email notifications
#notifications:
#  disabled: true
