name: Windows

on: [push, pull_request]
jobs:
  build:
    name: >-
      windows-latest  Ruby: ${{ matrix.ruby }}
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.4.x', '2.5.x', '2.6.x', '9.9.x' ]
    steps:
      - name: repo checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 10
      - name: load ruby, update gcc
        uses: MSP-Greg/actions-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
          base: update
      - name: update RubyGems, Bundler
        run:  gem update --system --no-document --conservative
      - name: bundle install
        run:  bundle install --jobs=3 --retry=3
      - name: test
        run:  |
          ruby -v
          bundle exec rake
        env:
          CI: true
